// GENERATED by typespec-http-zod from the TypeSpec service definition. DO NOT EDIT.
// Recompile the spec that produced it; edits here are overwritten on the next run.

import { z } from "zod";
import type { ResponseArm } from "./runtime.gen.js";

/** An inferred type narrowed to what JSON can carry: an optional property is absent or a value. */
type Exact<T> = { [K in keyof T as undefined extends T[K] ? never : K]: T[K] } & {
	[K in keyof T as undefined extends T[K] ? K : never]?: Exclude<T[K], undefined>;
};

export const thingSchema = z.object({
	when: z.string(),
	link: z.string(),
	plain: z.string(),
	id: z.string(),
});
export type Thing = Exact<z.infer<typeof thingSchema>>;

export const tResponses = [{ status: 200, schema: thingSchema }] satisfies readonly ResponseArm[];
