// GENERATED by typespec-hono from the TypeSpec service definition. DO NOT EDIT.
// Recompile the spec that produced it; edits here are overwritten on the next run.

import { zValidator } from "@hono/zod-validator";
import type { Context, Hono, Input } from "hono";
import { z } from "zod";
import type { AppEnv, Awaitable, Ctx, Result, RouteDeps } from "./runtime.gen.js";
import { xBody, xQuery, xResponses } from "./schemas.gen.js";

/**
 * One method per operation, each concretely typed from the schemas it validates against.
 *
 * There is no cast anywhere in this file, and no dynamic lookup: the generated call sites name the
 * method, so an implementation whose input or output does not match the contract fails to compile.
 */
export interface Operations {
	x(ctx: Ctx, input: z.infer<typeof xQuery> & z.infer<typeof xBody>): Awaitable<Result<void>>;
}

/**
 * One alias per operation, so a handler can live beside the module it belongs to.
 *
 * **Derived by indexed access, never restated.** An indexed access into Operations cannot drift
 * from the interface; a second hand-written signature could, and a signature that silently disagrees
 * with the contract is the whole failure mode this emitter exists to remove.
 */
export type XHandler = Operations["x"];

/**
 * **There is deliberately NO exported HandlersFor alias to annotate the factory with.**
 *
 * There was one, and it silently disabled the guard below. Annotating widens the value to
 * Operations, so T infers as Operations, Exclude<keyof T, keyof Operations> is never, and the
 * surplus-key constraint evaporates. Measured: a handler for an operation the spec no longer
 * declares produced no error at all through the annotated form, and TS2345 without it.
 *
 * Write the factory unannotated, inference then carries the real shape into registerRoutes:
 *
 *     const handlersFor = (c) => backendFor(c.env);
 *     registerRoutes(app, handlersFor, deps);
 */

/**
 * Refuses a handler set carrying an operation the spec no longer declares.
 *
 * **Removal is the change the type system misses, and it is the one that matters most.** Adding an
 * operation is a missing property; changing one is a wrong signature; both fail loudly. Removing one
 * leaves a handler that compiles forever against a route nobody mounts.
 *
 * The excess-property check catches it, but ONLY on an object literal assigned straight to an
 * annotated target. Mapping every surplus key to never makes the refusal structural instead: a key
 * outside Operations can only be satisfied by a value that cannot exist.
 */
export type Exhaustive<T> = T & Record<Exclude<keyof T, keyof Operations>, never>;

/** Mount every operation the service declares. */
export function registerRoutes<T extends Operations>(
	app: Hono<AppEnv>,
	handlersFor: <P extends string, I extends Input>(c: Context<AppEnv, P, I>) => Exhaustive<T>,
	deps: RouteDeps,
) {
	return app.post(
		"/x",
		zValidator("query", xQuery, deps.invalid),
		zValidator("json", xBody, deps.invalid),
		async (c) => {
			const ctx = deps.context(c, "none");
			if (ctx === null) return deps.noContext(c);
			return deps.respond(
				c,
				xResponses,
				await handlersFor(c).x(ctx, {
					...c.req.valid("query"),
					...c.req.valid("json"),
				}),
			);
		},
	);
}
