// GENERATED by typespec-http-zod from the TypeSpec service definition. DO NOT EDIT.
// Recompile the spec that produced it; edits here are overwritten on the next run.

import { z } from "zod";
import type { ResponseArm } from "./runtime.gen.js";

export const xQuery = z.object({
	q: z.string().optional(),
});
export const xBody = z.record(z.string(), z.string());
export const xResponses = [{ status: 204, schema: undefined }] satisfies readonly ResponseArm[];
