import { renderSecurity, type SecurityRequirement } from "./security.js";
import {
	isRawBinaryMediaType,
	objectKey,
	type EmittedRoute,
	type EmittedService,
	type RouteSchemaNames,
} from "typespec-http-zod";

/**
 * The header every emitted file carries.
 *
 * **`DO NOT EDIT` says what not to do and not what to do instead.** Only the project knows the
 * command that regenerates, so `regenerate-hint` supplies it and the generic line stands otherwise.
 * The library honours the same option for the files it writes; a hint reaching three files out of
 * five would be worse than none, because the two it missed are the two a reader opens first.
 */
export function generatedBanner(hint: string | undefined): string {
	const second =
		hint === undefined
			? "// Recompile the spec that produced it; edits here are overwritten on the next run."
			: `// Regenerate with: ${hint}`;
	return `// GENERATED by typespec-hono from the TypeSpec service definition. DO NOT EDIT.\n${second}\n`;
}

/** A parameter name Hono can carry verbatim. Measured against Hono, not assumed. */
const PLAIN_PATH_PARAMETER = /^[A-Za-z0-9_.~-]+$/;

/**
 * TypeSpec publishes `/widgets/{widget-id}`; Hono routes on `/widgets/:widget-id`.
 *
 * **This used to match `\w+`, so any parameter carrying a hyphen was left ALONE.**
 * `@path("thing-id")` produced the literal route `/things/{thing-id}`, mounted, counted by every arm
 * that counts routes, and reachable by nobody. It answered 404 to the only requests it was for. Hono
 * handles `:thing-id` and `:x.y` perfectly well; the narrow character class was ours.
 *
 * A name that is not plain is REFUSED rather than approximated, and the route stays at the literal
 * template so it matches nothing rather than matching the wrong thing.
 *
 * **This is about the NAME, not about RFC 6570 operators.** An earlier version of this comment
 * claimed `{+path}` or `{tag*}` would survive into the name and that `*` would become Hono's
 * wildcard. Measured, that is false: `@typespec/http` resolves the operator before this emitter sees
 * the path, and `@typespec/openapi3` strips it from the published document too, so both artefacts say
 * `/files{path}` and agree. What actually reaches here is a wire name from `@path("...")`, and the
 * forms that fail are a space, `+` and `!`. `*` is rejected by `@typespec/http` before it arrives.
 *
 * **This runs at RENDER time, not during collection.** It used to run inside `collectRoutes`, which
 * put one framework's spelling into the shared intermediate representation and refused the whole
 * operation (validators included) over a template no router could mount. What a request body must
 * look like does not depend on that.
 */
export function toHonoPath(
	template: string,
	refuse: (template: string, name: string) => void,
	/**
	 * Wire names the document says carry RFC 6570 reserved expansion, so their value may contain `/`.
	 *
	 * **A hierarchical identifier is ONE value, not several segments.** An Obsidian note is
	 * `areas/health.md`; an S3 key and a GitHub file path are the same shape. A router that stops at
	 * the first `/` binds `areas` and 404s the rest. Hono spells the greedy form `:name{.+}`.
	 *
	 * Read from `EmittedRoute.reservedPathParameters`, which the library resolves from `allowReserved`
	 * on the parameter. **Never from the template**: the operator does not survive to `route.path`,
	 * `@typespec/http` strips it, and it can also be set with no operator in the template at all, so
	 * the template is a derived artefact rather than the source of truth.
	 */
	reserved: ReadonlySet<string> = new Set(),
): string {
	return template.replace(/\{([^}]+)\}/g, (match, name: string) => {
		/**
		 * **The name check comes FIRST and is unconditional.** A name Hono cannot carry is refused
		 * whether or not it is reserved: greedy matching does not make a space or a `+` in a parameter
		 * name expressible, and letting one through because another flag was set would mount a route
		 * matching the wrong requests rather than one that fails.
		 */
		if (!PLAIN_PATH_PARAMETER.test(name)) {
			refuse(template, name);
			return match;
		}
		return reserved.has(name) ? `:${name}{.+}` : `:${name}`;
	});
}

/**
 * The verb Hono actually dispatches under.
 *
 * `HEAD` is rewritten to `GET` before matching -- `hono-base.js` does it unconditionally at the top
 * of `#dispatch` -- so a route registered under `HEAD` is never reached. Registering it under `GET`
 * is what makes it reachable, and Hono strips the response body for a real HEAD request itself,
 * which is what RFC 9110 requires.
 *
 * The original verb is still available to the handler: `c.req.method` reads `HEAD` on a HEAD
 * request even after the rewrite, which is what lets one registration serve both.
 */
const REGISTRATION_VERB: Readonly<Record<string, string>> = { HEAD: "GET" };

function registrationVerbOf(verb: string): string {
	return REGISTRATION_VERB[verb] ?? verb;
}

/** `GET` -> `get`. Hono's per-verb helpers are the idiom; `app.on` is the escape hatch. */
const HONO_METHOD: Readonly<Record<string, string>> = {
	GET: "get",
	POST: "post",
	PUT: "put",
	PATCH: "patch",
	DELETE: "delete",
};

/**
 * A request location, as the DOCUMENT names it, mapped to the target `@hono/zod-validator` reads.
 *
 * **The two vocabularies are not the same, and only one of them is a contract fact.** OpenAPI says
 * `path`, `query`, `header` and a request body; zValidator says `param`, `query`, `header` and
 * `json`. The library publishes the first because that is what the document states; translating is
 * this package's job, and it is a map rather than a coincidence.
 */
const VALIDATOR_TARGET = {
	path: "param",
	query: "query",
	header: "header",
	body: "json",
} as const;

/**
 * The `@hono/zod-validator` target for a request body, decided by what the wire actually carries.
 *
 * **This was `"json"` unconditionally, and that made every non-JSON body unservable.**
 * `zValidator("json", ...)` reads `c.req.json()`, so a `multipart/form-data` upload was parsed as JSON
 * and refused. Measured: 17 such registrations in `payload/multipart` alone, and **11 of the 17
 * request bodies in the Swagger Petstore are not JSON**, 5 urlencoded, 5 XML, 1 octet-stream.
 *
 * Hono's own target for both multipart and urlencoded is `"form"`, `c.req.parseBody()` handles the
 * two together, which is why one branch covers both.
 *
 * **Anything else stays `"json"` deliberately.** A media type this function does not recognise is
 * not a licence to guess: `application/xml` has no Hono target and no Zod representation the document
 * justifies, so it keeps the existing behaviour rather than acquiring a new one on the way past. That
 * gap is real and is stated in the README rather than papered over here.
 */
function targetForMediaType(type: string): string | undefined {
	if (type === "application/x-www-form-urlencoded" || type.startsWith("multipart/")) return "form";
	// `application/json`, and the `+json` structured suffix RFC 6839 defines.
	if (type === "application/json" || type.endsWith("+json")) return VALIDATOR_TARGET.body;
	return undefined;
}

interface BodyValidation {
	/** `[media type, zValidator target]`, one per type this can parse, in the document's order. */
	readonly byType: readonly (readonly [string, string])[];
	/** Types the document declares that no `zValidator` target can parse. */
	readonly unparseable: readonly string[];
}

/**
 * Which `zValidator` target parses each media type the request may carry.
 *
 * **This used to return ONE target for the whole route, and that was silently wrong for a mixed
 * body.** Which parser applies is decided by the caller's `Content-Type` at REQUEST time;
 * `zValidator`'s target is fixed at generation time. So a route declaring
 * `application/json | application/xml | application/x-www-form-urlencoded` -- which is `addPet` in
 * the Swagger Petstore, and 11 of its 17 request bodies are not JSON -- got `zValidator("json")` and
 * rejected every form-encoded body with a 400, raising no diagnostic at all.
 *
 * The answer is to decide at request time, which is the only time the answer exists. Where the
 * document declares one parseable type this still emits a single `zValidator` exactly as before.
 *
 * **`application/xml` and friends are reported, not guessed at.** There is no Hono parser and no
 * Zod representation for XML, and adding an XML dependency to a Zod emitter is not a trade this
 * package should make. Naming them is what stops a consumer believing a route is validated when it
 * is not -- the previous behaviour said nothing and rejected them.
 */
function bodyValidationFor(contentTypes: readonly string[]): BodyValidation {
	if (contentTypes.length === 0) return { byType: [["", VALIDATOR_TARGET.body]], unparseable: [] };
	const byType: (readonly [string, string])[] = [];
	const unparseable: string[] = [];
	for (const type of contentTypes) {
		const target = targetForMediaType(type);
		if (target === undefined) unparseable.push(type);
		else byType.push([type, target]);
	}
	return { byType, unparseable };
}

interface AppRoute {
	readonly route: EmittedRoute;
	readonly names: RouteSchemaNames;
	/** `[zValidator target, the identifier holding its schema]`, in the order they are applied. */
	readonly validators: readonly (readonly [string, string])[];
	/**
	 * Set where the document declares request media types needing DIFFERENT parsers, so the validator
	 * is chosen from the request's `Content-Type` rather than at generation time.
	 */
	readonly dispatched:
		| { readonly byType: readonly (readonly [string, string])[]; readonly identifier: string }
		| undefined;
	/**
	 * Set where the document publishes `requestBody.required: false`, so the body is mounted by
	 * `optionalBody` and a request carrying none is let through rather than refused.
	 */
	readonly optional: { readonly target: string; readonly identifier: string } | undefined;
}

/**
 * How an unparsed body reaches the handler, and as what.
 *
 * **This was always `c.req.text()` typed as `string`, and for a binary body that silently
 * corrupts.** `text()` UTF-8-decodes, so every byte outside ASCII becomes U+FFFD. Measured against a
 * Petstore `application/octet-stream` upload under `wrangler dev`:
 *
 * ```
 * sent     : 89 50 4e 47 0d 0a 1a 0a ff d8 ff e0 00 10 4a 46 49 46      (18 bytes)
 * received : fffd 50 4e 47 0d 0a 1a 0a fffd fffd fffd fffd 00 10 4a 46 49 46
 * ```
 *
 * Five bytes destroyed, unrecoverably, and the request answered **200**. Success status, corrupt
 * payload, no signal. The worst shape a defect can take.
 *
 * **`rawBodyProperty` conflated two different requirements, which is why one reader looked
 * sufficient.** Its docblock justifies `text()` by a webhook's MAC covering exactly what arrived, true,
 * and true only when what arrived is text. An upload is the other case, and it needs the bytes.
 * `isRawBinaryMediaType` is the library's own rule for telling them apart, already applied on the
 * response side; importing it rather than re-deriving it is what keeps the two halves from disagreeing
 * again.
 *
 * **A binary body is handed over as the UNREAD stream, not as an `ArrayBuffer`.** `arrayBuffer()`
 * materialises the whole payload in the isolate, and a Worker gets 128 MB against a request-body
 * limit of 100 MB, so an upload at the documented maximum cannot be served at all. The document
 * publishes only `contentMediaType` for such a body - **nothing a validator can check** - so
 * materialising it produced a value nothing validates, at the cost of the one thing a gateway
 * actually wants to do with it: pipe it somewhere without touching it.
 *
 * Handing over the stream is strictly more capable. A handler wanting the bytes writes
 * `await new Response(input.body).arrayBuffer()`; a handler wanting to stream into R2 pipes it. The
 * reverse was not possible.
 *
 * **It costs no ambient dependency, which was assumed to be a trade and then measured.**
 * `ReadableStream` needs `lib.dom`, `@cloudflare/workers-types` or `@types/node` - and the generated
 * server has needed exactly the same lib since it was first emitted, because it names `Response`.
 * Whatever a project already supplies to satisfy that declares `ReadableStream` too, so there is no
 * project that could build the old output and cannot build this. `test/streambody/` asserts both
 * halves; `test/compiles.test.ts` cannot, because it sets `target` without `lib` and TypeScript then
 * defaults to the `.full` variant, which includes DOM.
 *
 * `null` because a request may carry no body at all, which is what the platform reports.
 */
function rawBodyReaderFor(contentTypes: readonly string[]): {
	readonly call: string;
	readonly type: string;
} {
	return isRawBinaryMediaType(contentTypes)
		? { call: "c.req.raw.body", type: "ReadableStream<Uint8Array> | null" }
		: { call: "await c.req.text()", type: "string" };
}

/**
 * Everything an operation's input is made of, as a TypeScript type built from the schemas the library
 * declared.
 *
 * `z.infer` rather than a restatement: the handler receives exactly what the validators produced, so
 * deriving the type from the same consts is what makes the call site check itself. A restated
 * interface would be a second source of truth that drifts.
 */
/**
 * The validators whose fields are INTERSECTED into the input, as opposed to named beside it.
 *
 * Shared with the decision to emit `Fields<>` at all, so "is this helper used" is answered by the
 * same code that uses it rather than by searching the rendered output - an unused type declaration
 * fails `noUnusedLocals`, which a generated file has to pass like any other.
 */
function intersectedValidatorsOf(entry: AppRoute): readonly string[] {
	const bodyProperty = entry.route.bodyProperty;
	const bodyName = entry.names.body;
	return entry.validators
		.filter(([, name]) => bodyProperty === undefined || name !== bodyName)
		.map(([, name]) => name);
}

function inputTypeOf(entry: AppRoute): string | undefined {
	/**
	 * **A body the document says must not be flattened is NAMED, not intersected.**
	 *
	 * `EmittedRoute.bodyProperty` is set for a body with an indexer. Intersected, its index signature
	 * is imposed on every sibling, so an optional `@query q?: string` beside a `Record<string>` body
	 * failed with `TS2345: 'q' is incompatible with index signature` and the generated server did not
	 * compile at all. It was wrong before it failed to compile, too: the document states the
	 * parameters and the body separately, and merged, a body key named `q` silently overwrites the
	 * query parameter of that name.
	 */
	const bodyProperty = entry.route.bodyProperty;
	/**
	 * **The body validator is found by its SCHEMA, never by its target.** A JSON body validates under
	 * `"json"` and a form body under `"form"`, so keying on the JSON target silently missed every
	 * form - measured on a clean install, `@header contentType: "application/x-www-form-urlencoded"`
	 * with a `Record` body still emitted the intersection and still did not compile. The schema
	 * identifier is the same fact whichever parser reads it.
	 */
	const bodyName = entry.names.body;
	/**
	 * **`Fields<>` is what stops an EMPTY validator poisoning the intersection.**
	 *
	 * Zod 4 infers `Record<string, never>` for `z.object({})` - "no string key may exist" - which is
	 * a correct reading of an empty object on its own and lethal in an intersection: `{ id: string }
	 * & Record<string, never>` makes `id` into `string & never`, so the input type is uninhabitable
	 * and the generated call site fails `tsc` inside `app.gen.ts` itself. Measured on
	 * `model Empty {}` as an optional body: `TS2345: Argument of type '{ id: string; }' is not
	 * assignable to parameter of type '{ id: string; } & Record<string, never>'`.
	 *
	 * The emitted server not compiling is the worst shape available to this emitter, and no arm saw
	 * it because no fixture declared an empty model.
	 */
	const parts = intersectedValidatorsOf(entry).map((name) => `Fields<z.infer<typeof ${name}>>`);
	if (bodyProperty !== undefined && bodyName !== undefined) {
		/**
		 * **Optional on the input when the document says the body is optional**, which is the whole
		 * reason such a body is named rather than merged: `c.req.valid(...)` reads `undefined` when
		 * none arrived, and a merge has no way to say that. Spelled `| undefined` as every other
		 * optional here is, because `exactOptionalPropertyTypes` is on.
		 */
		const optionalMark = entry.route.optionalBody ? "?" : "";
		const optionalValue = entry.route.optionalBody ? " | undefined" : "";
		parts.push(
			`{ ${objectKey(bodyProperty)}${optionalMark}: z.infer<typeof ${bodyName}>${optionalValue} }`,
		);
	}
	if (entry.route.rawBodyProperty !== undefined) {
		const reader = rawBodyReaderFor(entry.route.requestContentTypes);
		parts.push(`{ ${objectKey(entry.route.rawBodyProperty)}: ${reader.type} }`);
	}
	return parts.length === 0 ? undefined : parts.join(" & ");
}

/**
 * `getWidget` -> `GetWidget`, `Avatar_getAvatarAsJson` -> `Avatar_getAvatarAsJson`.
 *
 * Only the first character moves. An operation id is already the name the DOCUMENT publishes, and
 * rewriting more of it would invent a second spelling of a contract fact for the sake of house style
 *. The `_` that `resolveOperationId` inserts is part of the published name.
 */
function capitaliseId(operationId: string): string {
	return `${operationId.charAt(0).toUpperCase()}${operationId.slice(1)}`;
}

/** The one thing a Hono server cannot express, handed back rather than thrown. */
export interface RenderRefusals {
	readonly unsupportedPathTemplate: (route: EmittedRoute, template: string, name: string) => void;
	readonly unvalidatableMediaType: (route: EmittedRoute, types: readonly string[]) => void;
}

/** The schema identifier a dispatched body validates against. */
function identifierOf(entry: AppRoute): string {
	return entry.dispatched?.identifier ?? "";
}

/**
 * The resource a route belongs to (its first path segment) or `undefined` when it has none.
 *
 * **A parameter is not a resource.** `/{id}/things` has no groupable head: mounting a sub-app at
 * `/:id` would make the parameter the resource name, which is not what the document says and not what
 * anybody would write.
 */
function resourceOf(path: string): string | undefined {
	const segment = path.split("/").filter((part) => part !== "")[0];
	if (segment === undefined || segment.startsWith(":") || segment.startsWith("{")) return undefined;
	return segment;
}

/**
 * A safe identifier for a resource's sub-app.
 *
 * Suffixed rather than named for the resource alone: every validator this file imports is named from
 * an operation id, and a bare `widgets` could collide with one. A collision here is a file that does
 * not compile, which is cheap to prevent and expensive to debug in generated output.
 */
function subAppNameOf(resource: string): string {
	const cleaned = resource.replace(/[^A-Za-z0-9]+(.)?/g, (_match, next: string | undefined) =>
		next === undefined ? "" : next.toUpperCase(),
	);
	const head = cleaned.charAt(0).toLowerCase() + cleaned.slice(1);
	return `${/^[A-Za-z_$]/.test(head) ? head : `r${head}`}Routes`;
}

/**
 * The generated Hono server.
 *
 * **This replaces a data table that a hand-written loop interpreted at run time.** The emitter knew,
 * per operation, which validators applied and what the call looked like, and then flattened all of it
 * into one homogeneous array, so the consumer had to recover it dynamically and could not. Emitting
 * the call sites keeps that knowledge, and every one of them is monomorphic and checked.
 *
 * **Plain `Hono` and `@hono/zod-validator`, deliberately not `@hono/zod-openapi`.** The latter is
 * the same validation plus a document generated FROM the code, spec-last, and a second source of
 * truth competing with the one `@typespec/openapi3` publishes from the spec. We want its validation,
 * not its documentation.
 *
 * **It declares no schema of its own.** Every validator this file names was declared by
 * `typespec-http-zod` into `schemas.gen.ts` and is imported by name. That is what makes the two
 * packages one emitter rather than two that must agree by coincidence, and it is why a consumer who
 * wants the validators without a server can simply not install this one.
 */
export function renderApp(
	emitted: EmittedService,
	refuse: RenderRefusals,
	/**
	 * Every path the DOCUMENT says this service is served under. All of them are mounted.
	 *
	 * **An OpenAPI path is relative to its server**, so `@server("/api/v1")` plus `/accounts` means
	 * the document publishes `/api/v1/accounts`. Mounting at the root made every client generated from
	 * the document, and every "try it" in a rendered document, 404.
	 */
	basePaths: readonly string[] = [],
	/**
	 * What the DOCUMENT says a caller must satisfy, per operation id.
	 *
	 * **Resolved by the caller rather than read off `EmittedRoute`**, because which schemes an
	 * operation accepts is a fact about the HTTP program and not part of the validator IR the library
	 * publishes. Keeping it out of that IR is what stops a Hono concern leaking into a package whose
	 * audience is wider.
	 */
	securityFor?: (verb: string, path: string) => readonly SecurityRequirement[],
): string {
	const mounted: AppRoute[] = emitted.routes.flatMap((route) => {
		let dispatched:
			| { byType: readonly (readonly [string, string])[]; identifier: string }
			| undefined;
		const names = emitted.schemaNames.get(route.operationId);
		// The library declares a `Responses` const for every operation, so a missing entry is a bug in
		// this package's pairing rather than a spec the emitter chose not to serve.
		if (names === undefined) return [];
		const validators: (readonly [string, string])[] = [];
		let optional: { readonly target: string; readonly identifier: string } | undefined;
		for (const location of ["path", "query", "header", "body"] as const) {
			const identifier = names[location];
			if (identifier === undefined) continue;
			if (location !== "body") {
				validators.push([VALIDATOR_TARGET[location], identifier]);
				continue;
			}
			/**
			 * The body is the one location whose parser the document does not fix at generation time.
			 * Where it declares a single parseable media type this is one `zValidator`, unchanged. Where
			 * it declares several, the choice belongs to the caller's `Content-Type` and is made then.
			 */
			const body = bodyValidationFor(route.requestContentTypes);
			if (body.unparseable.length > 0) refuse.unvalidatableMediaType(route, body.unparseable);
			if (body.byType.length === 0) continue;
			const targets = [...new Set(body.byType.map(([, target]) => target))];
			if (targets.length === 1) {
				/**
				 * **An optional body is mounted by `optionalBody`, not `zValidator`**, so a request
				 * carrying none is let through instead of refused - see the runtime's docblock for the
				 * 400 that produced. It publishes under the canonical body slot whichever parser read
				 * it, exactly as `byContentType` does, so the handler reads it the same way everywhere.
				 */
				if (route.optionalBody) {
					validators.push([VALIDATOR_TARGET.body, identifier]);
					optional = { target: targets[0] as string, identifier };
					continue;
				}
				/**
				 * **A required body keeps `zValidator`, and unifying it was tried and reverted.**
				 *
				 * `zValidator` raises `HTTPException` on a body that is not the JSON its content type
				 * claims, BEFORE `deps.invalid` runs, so that 400 is `text/plain` and escapes the app's
				 * error envelope. Routing every body through `byContentType` fixes it and is the obvious
				 * move - one code path, one place the rejection is decided.
				 *
				 * **It is a breaking change to the RUNTIME CONTRACT, not just to emitted output.** An app
				 * that points `runtime-module` at its own module would have to export `byContentType`,
				 * which today it needs only if some operation declares several request media types - rare
				 * enough that no consumer exports it. Measured: 15 arms red, every one of them an app
				 * whose substituted module has no such export.
				 *
				 * The envelope gap is real and stays open for a required single-media-type body. Closing
				 * it wants a form that adds no export to the runtime contract - most likely emitting the
				 * middleware into `app.gen.ts` itself - and that is its own change, not a line here.
				 */
				validators.push([targets[0] as string, identifier]);
				continue;
			}
			/**
			 * **Recorded as an ordinary body validator as well**, because `byContentType` publishes what
			 * it validated under the body target whichever parser produced it. So a dispatched route is
			 * the same shape as every other one downstream: the handler's input type includes the body,
			 * and the handler reads it with one `c.req.valid` like anywhere else. What differs is only
			 * which middleware is emitted, below.
			 */
			validators.push([VALIDATOR_TARGET.body, identifier]);
			dispatched = { byType: body.byType, identifier };
		}
		return [{ route, names, validators, dispatched, optional }];
	});

	const entries = mounted;

	/**
	 * **One registration per verb+path, not per operation.**
	 *
	 * TypeSpec models content negotiation as several operations on one route; OpenAPI models it as one
	 * path entry whose response lists every media type. This emitter used to register all of them, and
	 * Hono matches in registration order, so every operation after the first was dead code that looked
	 * mounted, and the only symptom was an operation count two higher than the document's.
	 */
	const grouped = new Map<string, AppRoute[]>();
	for (const entry of entries) {
		const slot = `${entry.route.verb} ${entry.route.path}`;
		grouped.set(slot, [...(grouped.get(slot) ?? []), entry]);
	}

	/**
	 * The input type of an operation that declares no input.
	 *
	 * **Every operation takes `(ctx, input)`, including this one.** A surface written once against
	 * `Operations` - an RPC entrypoint, a proxy, any uniform dispatch - is typed `(ctx, input)`, and
	 * TypeScript refuses a function with MORE parameters than the signature it is assigned to. So a
	 * single parameterless operation emitting `(ctx)` made the whole surface unassignable, measured as
	 * `TS2322: Target signature provides too few arguments. Expected 2 or more, but got 1.`
	 *
	 * **Adding the parameter breaks nothing**, which is what makes this the right shape rather than a
	 * trade: FEWER parameters is always assignable, so a handler already written `(ctx) => ...` keeps
	 * compiling untouched. `test/openmodel/treaty.test.ts` holds both halves.
	 *
	 * `Record<string, never>` rather than `{}`, because `{}` in TypeScript means "anything but null",
	 * which is the opposite of the claim being made.
	 */
	const EMPTY_INPUT = "Record<string, never>";
	/**
	 * Emitted only where an operation INTERSECTS a validator's fields, which is what names it.
	 *
	 * Decided from the routes rather than by searching the rendered text - the mistake that once
	 * dropped the `byContentType` import when a call gained an argument.
	 */
	const usesFields = entries.some((entry) => intersectedValidatorsOf(entry).length > 0);
	const fieldsHelper = usesFields
		? `/**
 * A validator's fields, or nothing at all when it declares none.
 *
 * **Zod 4 infers \`Record<string, never>\` for \`z.object({})\`.** That is a fair reading on its own -
 * no string key may exist - and lethal in an intersection: \`{ id: string } & Record<string, never>\`
 * makes \`id\` into \`string & never\`, so the input type is uninhabitable and the call site below
 * cannot compile. An empty model contributes nothing to an operation's input, and \`unknown\` is the
 * identity of \`&\`, so that is what it becomes.
 *
 * A DICTIONARY body is not this: \`Record<unknown>\` has a value type, so it survives untouched.
 */
type Fields<T> = string extends keyof T ? ([T[string]] extends [never] ? unknown : T) : T;

`
		: "";
	const methods = entries.map((entry) => {
		const { route, names } = entry;
		/**
		 * A negotiated member's `accept` is not in its validator (the negotiation supplies it) but it
		 * IS in the operation's declared input, so the interface has to keep it. The literal is known
		 * exactly: it is the only value that reaches this member.
		 */
		const negotiated =
			(grouped.get(`${route.verb} ${route.path}`)?.length ?? 0) > 1 && route.accept !== undefined
				? `{ ${objectKey(route.accept.name)}: ${JSON.stringify(route.accept.value)} }`
				: undefined;
		const validated = inputTypeOf(entry);
		const input =
			negotiated === undefined
				? validated
				: validated === undefined
					? negotiated
					: `${validated} & ${negotiated}`;
		/**
		 * **The RETURN type is the producer's view; the input type is left exactly as it arrives.**
		 *
		 * A handler receives whatever the validator let through, so an input carrying
		 * `[key: string]: unknown`, `T | undefined` on an optional, and mutable arrays is an honest
		 * description of the value in hand. Returning is the opposite direction: the handler supplies
		 * something the application already holds, and each of those becomes an obligation rather than
		 * a description. See `Produced` below for what that cost, measured.
		 *
		 * `typespec-http-zod` fixes the same three things on its contract types. None of it reaches
		 * here on its own, because this signature is derived from `z.infer` rather than from those
		 * types - which is exactly the half-fix `test/openmodel/` exists to catch.
		 */
		/**
		 * **The ENVELOPE a handler has to be able to say, beside the body it returns.**
		 *
		 * `@statusCode` and `@header` properties are stripped from the body schema - correctly, they
		 * are not body - so a return type derived from that schema alone could not carry them. The arms
		 * name them anyway: `{ headers: [{ property: "correlationId" }] }` tells `respond` to read a
		 * property off the returned value, and `when: { property: "statusCode" }` tells it which arm
		 * the handler meant. Measured before this existed, on `payload__head`:
		 * `Awaitable<Result<void>>` against an arm naming two header properties, so the emitter
		 * published an envelope contract nothing could satisfy.
		 *
		 * Only the SUCCESS statuses count. `responseHeaders` covers error responses too, and a header
		 * declared on a 404 is the error body's business rather than something a handler returns.
		 */
		const successStatuses = route.statusSelector?.statuses ?? [route.statusCode];
		const envelope: string[] = [];
		if (route.statusSelector !== undefined) {
			envelope.push(
				`${objectKey(route.statusSelector.property)}: ${route.statusSelector.statuses.join(" | ")}`,
			);
		}
		const headerEntries = route.responseHeaders.filter((entry) =>
			successStatuses.includes(entry.status as number),
		);
		const declaredOn = new Map<string, { count: number; type: string }>();
		for (const entry of headerEntries) {
			for (const header of entry.headers) {
				const seen = declaredOn.get(header.property);
				declaredOn.set(header.property, {
					count: (seen?.count ?? 0) + 1,
					type: header.type,
				});
			}
		}
		for (const [property, { count, type }] of declaredOn) {
			// Required only where EVERY success status declares it; otherwise the handler cannot know
			// which status it is answering with until it has chosen one.
			const optional =
				count === headerEntries.length && headerEntries.length === successStatuses.length;
			envelope.push(`${objectKey(property)}${optional ? "" : "?"}: ${type}`);
		}
		const envelopeType = envelope.length === 0 ? undefined : `{ ${envelope.join("; ")} }`;
		const body =
			names.response === undefined ? undefined : `Produced<z.infer<typeof ${names.response}>>`;
		const output =
			body === undefined
				? (envelopeType ?? "void")
				: envelopeType === undefined
					? body
					: `${body} & ${envelopeType}`;
		const signature = `ctx: Ctx, input: ${input ?? EMPTY_INPUT}`;
		const doc = route.summary === undefined ? "" : `\t/** ${route.summary} */\n`;
		return `${doc}\t${route.operationId}(${signature}): Awaitable<Result<${output}>>;`;
	});

	/**
	 * Emitted only when an operation actually returns something, because a generated file has to pass
	 * `noUnusedLocals` like any other - the lint that has already failed this emitter twice over an
	 * import written for a construct the service did not use.
	 *
	 * **Decided from the routes, not by searching the rendered text.** Asking whether the output
	 * mentions a name is how this package lost the `byContentType` import: the call gained an argument
	 * and the substring stopped matching, so a module referenced a function it no longer imported.
	 */
	const mountsOptionalBody = entries.some((entry) => entry.optional !== undefined);
	const returnsAnything = entries.some((entry) => entry.names.response !== undefined);
	const declaredHelper = returnsAnything
		? `/**
 * What a handler must SUPPLY, as opposed to what it receives.
 *
 * **Three things that are true of an inferred type are not obligations on a producer**, and each one
 * made a value the application already held unreturnable:
 *
 * - an index signature, which an open model infers because its validator really does pass unknown
 *   keys through. TypeScript gives an interface no implicit index signature, so returning one meant
 *   spreading every level of the tree - a structural deep copy per response on one real service.
 *   **Only where the shape has declared keys beside it**: an index signature also arrives as a
 *   property's own declared type (\`Record<unknown>\`), where it is stated identically in both
 *   artefacts and stripping it would destroy the property. A string indexer means "dictionary" only
 *   when nothing is declared next to it, which is the same rule the contract types use;
 * - \`readonly\`, which a codebase commonly puts on the views its layers hand back. \`readonly T[]\`
 *   and \`T[]\` serialise to identical bytes, so mutability says nothing about a payload.
 *
 * The input types above keep both, deliberately: they describe the value in hand.
 *
 * **An explicit \`undefined\` on an optional property is NOT removed, and that was tried.** It looks
 * like the same class and is the opposite: dropping an index signature or adding \`readonly\` makes
 * MORE values assignable, and removing \`| undefined\` makes fewer. Measured, it broke
 * \`(ctx, input) => ok(input)\` - return what you were given - because what arrives carries it.
 *
 * Returning extra properties still works - excess-property checks apply to object literals, not to a
 * value the application already holds.
 */
type ProducedKeyOf<T> = keyof {
	[K in keyof T as string extends K
		? never
		: number extends K
			? never
			: symbol extends K
				? never
				: K]: 0;
};

type Produced<T> = T extends (...args: never[]) => unknown
	? T
	: T extends readonly (infer Element)[]
		? readonly Produced<Element>[]
		: T extends object
			? [ProducedKeyOf<T>] extends [never]
				? { readonly [K in keyof T]: Produced<T[K]> }
				: {
						readonly [K in keyof T as string extends K
							? never
							: number extends K
								? never
								: symbol extends K
									? never
									: K]: Produced<T[K]>;
					}
			: T;

`
		: "";

	const aliases = entries.map(
		(entry) =>
			`export type ${capitaliseId(entry.route.operationId)}Handler = Operations[${JSON.stringify(entry.route.operationId)}];`,
	);

	/**
	 * **Which resources get a sub-app, and which routes stay on the root.**
	 *
	 * **Hono's own guidance, followed rather than guessed at.** Its best-practices page says to use
	 * `app.route()` to build a larger application instead of Ruby-on-Rails-like controllers, while
	 * writing handlers *directly after the path definitions*, because a handler in a separate file
	 * cannot infer its path parameters. Both halves are honoured here: routes are grouped by resource,
	 * and every handler stays inline where `c.req.valid()` is typed.
	 *
	 * **Measured before relying on it:** `app.route(prefix, sub)` composes paths exactly, including a
	 * parameter in the prefix, and the PARENT's `app.routes` reports the fully composed path, so a
	 * route mounted through a sub-app is still countable, which is what every arm that counts routes
	 * depends on.
	 *
	 * A resource with ONE route is not a group, and gets no sub-app: that is what a Hono author writes,
	 * and a one-route sub-app is ceremony around a single line.
	 */
	const slotsByResource = new Map<string, string[]>();
	for (const slot of grouped.keys()) {
		const resource = resourceOf(slot.slice(slot.indexOf(" ") + 1));
		if (resource === undefined) continue;
		slotsByResource.set(resource, [...(slotsByResource.get(resource) ?? []), slot]);
	}
	const subApps = new Map<string, string>();
	for (const [resource, slots] of slotsByResource) {
		if (slots.length > 1) subApps.set(resource, subAppNameOf(resource));
	}

	/**
	 * Registration slots, which are not the same as negotiation groups.
	 *
	 * A HEAD operation shares GET's slot, because that is the only verb Hono will dispatch it under.
	 * So one slot can hold two groups -- the GET's and the HEAD's -- and the handler tells them apart
	 * with `c.req.method`. Everything else is one group per slot, exactly as before.
	 */
	const slots = new Map<string, AppRoute[][]>();
	for (const group of grouped.values()) {
		const { route } = group[0] as AppRoute;
		const slot = `${registrationVerbOf(route.verb)} ${route.path}`;
		slots.set(slot, [...(slots.get(slot) ?? []), group]);
	}

	const registrations = [...slots.values()].map(
		(groupsInSlot): { target: string; text: string; headOnly: boolean } => {
			const headGroups = groupsInSlot.filter((g) => (g[0] as AppRoute).route.verb === "HEAD");
			const plainGroups = groupsInSlot.filter((g) => (g[0] as AppRoute).route.verb !== "HEAD");
			/**
			 * When a path declares both, the GET is the one whose validators the single registration
			 * carries, and the HEAD branch is served from the same request. RFC 9110 defines HEAD as
			 * identical to GET apart from the response body, so the two accepting different inputs is a
			 * contradiction in the document rather than something to reconcile here.
			 */
			const primary = (plainGroups[0] ?? headGroups[0]) as AppRoute[];
			const headBranch = plainGroups.length > 0 ? headGroups[0] : undefined;
			const group = primary;
			const entry = group[0] as AppRoute;
			const { route, validators } = entry;
			/** A HEAD with no GET beside it: registered under GET, and guarded so only a HEAD reaches it. */
			const headOnly = plainGroups.length === 0 && headGroups.length > 0;
			const method = HONO_METHOD[registrationVerbOf(route.verb)] ?? "on";
			const path = toHonoPath(
				route.path,
				(template, name) => refuse.unsupportedPathTemplate(route, template, name),
				new Set(route.reservedPathParameters),
			);
			/**
			 * A route inside a sub-app is registered RELATIVE to the prefix it is mounted at.
			 *
			 * **The collection route is `"/"`, never the empty string.** Measured: `sub.get("/")` under
			 * `app.route("/widgets", sub)` answers `/widgets`, and `/widgets/` is a 404, so the composed
			 * path carries no trailing slash and the document's own path is what a caller reaches.
			 */
			const resource = resourceOf(path);
			const mountOn = resource === undefined ? undefined : subApps.get(resource);
			const target = mountOn ?? "app";
			const registeredPath =
				mountOn === undefined ? path : path.slice(`/${resource ?? ""}`.length) || "/";
			/**
			 * The scope gate goes FIRST, before any validator.
			 *
			 * A caller without the scope must be refused whatever their body looks like: validating first
			 * answers `400` to a request the contract says is not theirs to make, which tells somebody who
			 * may not call the operation at all which payloads are well-formed.
			 */
			/**
			 * **Emitted whenever the document declares ANY security, not only when it declares scopes.**
			 * `@useAuth(BearerAuth)` publishes `security: [{ "BearerAuth": [] }]` (no scopes) so a
			 * scopes-only gate covered OAuth2 and nothing else. Bearer, api-key and basic carried no gate at
			 * all and rested entirely on `deps.context` returning null, which answers "is somebody here"
			 * rather than "did they satisfy the scheme the contract names".
			 */
			const requirements = securityFor?.(route.verb, route.path) ?? [];
			const gate =
				requirements.length === 0 ? [] : [`\t\tdeps.authorize(${renderSecurity(requirements)}),`];
			/**
			 * A HEAD operation with no GET beside it is registered under GET, because that is the only verb
			 * Hono dispatches. The guard keeps the registration honest: a real GET is not in the document,
			 * so it gets the 404 it would have got before this route was registered at all, and only a HEAD
			 * reaches the validators and the handler.
			 *
			 * A plain middleware rather than `except()` from `hono/combine`, deliberately. `except` wraps the
			 * final handler, which erases its response type, and Hono's RPC client derives its entire surface
			 * from that type -- measured, `hc<typeof app>` resolved the wrapped route's body to `unknown`.
			 */
			/**
			 * Where the document declares request media types needing different parsers, the parser is
			 * chosen from the request's `Content-Type`. `byContentType` takes the body's schema and
			 * `deps.invalid` and validates with them, so it stands in for that target's `zValidator`
			 * rather than wrapping one, and publishes under the body target either way.
			 *
			 * **It used to wrap pre-built `zValidator`s and publish under whichever one ran, and that
			 * emitted code a consumer could not compile.** A plain `MiddlewareHandler` contributes no
			 * `Input` to Hono's chain, so `c.req.valid("json")` in the handler below was
			 * `TS2345: Argument of type '"json"' is not assignable to parameter of type '"header"'`, and
			 * the handler's declared input type omitted the body entirely because the body was not among
			 * the route's validators. One published slot removes both.
			 */
			const dispatch =
				entry.dispatched === undefined
					? []
					: [
							`\t\tbyContentType(${identifierOf(entry)}, deps.invalid, [`,
							...entry.dispatched.byType.map(
								([type, target]) => `\t\t\t[${JSON.stringify(type)}, ${JSON.stringify(target)}],`,
							),
							"\t\t]),",
						];
			const middleware = [
				...(headOnly ? ["\t\theadOnly,"] : []),
				...gate,
				...validators
					// The dispatched body's own `zValidator` is `byContentType`; emitting both would parse
					// the body twice and reject every media type but one. An optional body is the same
					// story with `optionalBody`, which additionally lets a bodyless request through.
					.filter(
						([target]) =>
							(entry.dispatched === undefined && entry.optional === undefined) ||
							target !== VALIDATOR_TARGET.body,
					)
					.map(
						([target, name]) => `\t\tzValidator(${JSON.stringify(target)}, ${name}, deps.invalid),`,
					),
				...dispatch,
				...(entry.optional === undefined
					? []
					: [
							`\t\toptionalBody(${entry.optional.identifier}, deps.invalid, ${JSON.stringify(entry.optional.target)}),`,
						]),
			];
			/**
			 * Whether the operation requires a caller, and NOTHING else about the caller.
			 *
			 * **This used to pass `"account"` or `"resource"`, chosen by how many path parameters the
			 * route had, and that was a rule no document states.** `@useAuth(NoAuth)` reaches OpenAPI as
			 * `security: []`, so "does this need a caller" is a contract fact and is generated. "Is this
			 * account-scoped or resource-scoped" is not: no OpenAPI keyword expresses it, and the
			 * path-parameter heuristic happened to fit the first consumer.
			 */
			const body: string[] = [];
			if (route.noAuth !== true) {
				body.push(`\t\t\tconst ctx = deps.context(c, "required");`);
				body.push("\t\t\tif (ctx === null) return deps.noContext(c);");
			} else {
				/**
				 * **The same null check as an authenticated route, and it is what removes a CAST from
				 * generated output.** This used to emit `deps.context(c, "none") as Ctx`, because one
				 * signature returning `C | null` cannot express "this argument makes null impossible". A cast
				 * in generated code is worse than one in hand-written code: nobody reviews it, and it
				 * reappears on every compile.
				 *
				 * **Overloading `context` was tried and is worse.** It removes the cast from here and puts
				 * one in every consumer's `deps`, because an overloaded property type stops contextually
				 * typing a single implementation. Measured, the wiring consumer lost inference on every
				 * hook. Trading a cast in generated code for a cast in hand-written code is the wrong
				 * direction.
				 *
				 * Checking is also more honest than asserting: an app that returns null here has said it
				 * could not build a context, and the old cast handed the handler that null typed as `Ctx`.
				 */
				body.push(`\t\t\tconst ctx = deps.context(c, "none");`);
				body.push("\t\t\tif (ctx === null) return deps.noContext(c);");
			}
			// A dispatched body is in `validators` under the body target like any other, so there is
			// nothing extra to spread: `byContentType` published it there whichever parser ran.
			// Same rule as `inputTypeOf`: the body is identified by its schema, not by its target.
			const bodyTarget = validators.find(([, name]) => name === entry.names.body)?.[0];
			const pieces = validators.map(([target]) =>
				/**
				 * A named body is assigned rather than spread, matching the input type above and the
				 * document, which states the parameters and the body as separate things.
				 */
				route.bodyProperty !== undefined && target === bodyTarget
					? `${objectKey(route.bodyProperty)}: c.req.valid(${JSON.stringify(target)})`
					: `...c.req.valid(${JSON.stringify(target)})`,
			);
			if (route.rawBodyProperty !== undefined) {
				// The bytes ARE the contract: a signature covers exactly what arrived, so parsing and
				// re-serialising would verify a different string than the sender signed. WHICH reader
				// preserves them depends on the media type, see `rawBodyReaderFor`.
				const reader = rawBodyReaderFor(route.requestContentTypes);
				pieces.push(`${objectKey(route.rawBodyProperty)}: ${reader.call}`);
			}
			const invoke = (member: AppRoute): string => {
				// The member's own `accept` literal, which its input type requires and which the shared
				// validator no longer supplies. We know it exactly: it is the branch we are in.
				const own =
					group.length > 1 && member.route.accept !== undefined
						? [
								`${objectKey(member.route.accept.name)}: ${JSON.stringify(member.route.accept.value)}`,
							]
						: [];
				const input = [...pieces, ...own];
				/**
				 * **Broken across lines rather than emitted as one.** Generated code is read far more often
				 * than it is written (in review, in a stack trace, in a diff) and a single call reached 219
				 * characters on a real service, against the 60-to-80 of every example in Hono's own
				 * documentation. Nothing about the behaviour changes; a reader's ability to see it does.
				 *
				 * A call with no input stays on one line, because wrapping it would add ceremony to something
				 * already short.
				 */
				/**
				 * **Indented literally, because the surrounding `+1 tab` only reaches the FIRST physical
				 * line.** A multi-line fragment keeps whatever tabs it was written with, so the depths here
				 * are absolute: the `return` sits at four, its arguments at five, and the handler's input
				 * properties at six.
				 */
				const call =
					input.length === 0
						? // An empty object, because every operation takes `(ctx, input)`. See `EMPTY_INPUT`.
							`handlersFor(c).${member.route.operationId}(ctx, {})`
						: [
								`handlersFor(c).${member.route.operationId}(ctx, {`,
								...input.map((piece) => `\t\t\t\t\t\t${piece},`),
								"\t\t\t\t\t})",
							].join("\n");
				return input.length === 0
					? `deps.respond(c, ${member.names.responses}, await ${call})`
					: [
							`deps.respond(`,
							`\t\t\t\t\tc,`,
							`\t\t\t\t\t${member.names.responses},`,
							`\t\t\t\t\tawait ${call},`,
							"\t\t\t\t)",
						].join("\n");
			};

			/**
			 * Both verbs on one path: `c.req.method` still reads `HEAD` after Hono's rewrite, so one
			 * registration serves both and each operation keeps its own handler and its own response arms.
			 * Hono strips the body on the HEAD branch itself.
			 *
			 * The HEAD branch is emitted FIRST because it is the narrower condition, and it returns, so the
			 * GET path below is reached only by a real GET.
			 */
			if (headBranch !== undefined) {
				const headEntry = headBranch[0] as AppRoute;
				body.push(`\t\t\tif (c.req.method === "HEAD") {`);
				body.push(`\t\t\t\treturn ${invoke(headEntry).replaceAll("\n", "\n\t")};`);
				body.push("\t\t\t}");
			}

			if (group.length === 1) {
				body.push(`\t\t\treturn ${invoke(entry)};`);
			} else {
				/**
				 * Several operations, one route: the caller's `Accept` chooses which one answers.
				 *
				 * The offered list and which operation serves each type are both read from the document.
				 * `selectContentType` applies RFC 9110 section 12.5.1 to them. It lives in the runtime rather than
				 * in `deps` because both halves are derivable, and an app forced to supply it would be
				 * re-implementing the standard.
				 */
				const offers = group.flatMap((member) =>
					member.route.responseContentTypes.map((contentType) => ({ contentType, member })),
				);
				const offered = `[${offers.map((offer) => JSON.stringify(offer.contentType)).join(", ")}]`;
				body.push(`\t\t\tconst served = selectContentType(c.req.header("accept"), ${offered});`);
				body.push(`\t\t\tif (served === undefined) return deps.notAcceptable(c, ${offered});`);
				for (const offer of offers) {
					body.push(
						`\t\t\tif (served === ${JSON.stringify(offer.contentType)}) return ${invoke(offer.member)};`,
					);
				}
				// `selectContentType` only ever returns a member of the list it was given, so this is
				// unreachable, and stating that is cheaper than a cast that would hide it if it were not.
				body.push(`\t\t\treturn deps.notAcceptable(c, ${offered});`);
			}
			/**
			 * **`app.on` takes the METHOD first, and we were not passing one.** Only five verbs have a
			 * dedicated Hono method; everything else (`HEAD`, `OPTIONS`, anything a spec invents) fell
			 * through to `app.on(path, handler)`, which Hono reads as `on(method, path)`. The route was
			 * emitted, counted by every arm that counted rows, and mounted nowhere.
			 */
			/**
			 * **Emitted as a CHAINED call fragment rather than a statement, and that is what makes Hono's
			 * RPC client work at all.** `hc<typeof app>` derives its entire surface from the `Schema` type
			 * parameter Hono accumulates through chaining, not from what is registered at run time. As
			 * separate statements each call's type was discarded, `registerRoutes` returned `void`, and
			 * measured in a fresh project `hc<typeof app>` resolved to **`unknown`**: not an empty client, an
			 * unusable one. A hand-chained app with the same sub-app-per-resource shape supports it
			 * perfectly, so the shape was never the obstacle, only the statements were.
			 */
			const text = [
				`\t\t.${method}(`,
				...(method === "on" ? [`\t\t\t${JSON.stringify(registrationVerbOf(route.verb))},`] : []),
				`\t\t\t${JSON.stringify(registeredPath)},`,
				...middleware.map((line) => `\t${line}`),
				"\t\t\tasync (c) => {",
				...body.map((line) => `\t${line}`),
				"\t\t\t},",
				"\t\t)",
			].join("\n");
			return { target, text, headOnly };
		},
	);

	/**
	 * Every identifier this file names, imported from the module that declares it.
	 *
	 * **Derived from what the rendered text actually references, not from what was available.** An
	 * unused import fails the lint a generated file has to pass like any other, and a missing one is a
	 * file that does not compile. Both have happened.
	 *
	 * **The text is TOKENISED and compared by equality, never matched name by name.** It used to build
	 * `new RegExp("\\b" + identifier + "\\b")` per name, and that was wrong twice over for any
	 * identifier containing a `$`, which TypeSpec permits in a model or operation name: `$` is an
	 * anchor in a regular expression, and escaping it alone does not help because `\b` is a WORD
	 * boundary and `$` is not a word character, so `\b\$select\b` cannot match either. Measured on
	 * `op list$Items(...): Item$Ref[]`, every identifier reported ABSENT, the whole
	 * `./schemas.gen.js` import was dropped, and the emitted file failed with four
	 * `TS2304: Cannot find name`. No diagnostic anywhere.
	 *
	 * Splitting on the language's own identifier rule and testing membership has neither failure: no
	 * metacharacter can be misread, and `Foo` cannot match `FooExtra`.
	 */
	const rendered = [...registrations.map((r) => r.text), ...methods, ...aliases].join("\n");
	const mentioned = new Set(rendered.match(/[A-Za-z_$][A-Za-z0-9_$]*/g) ?? []);
	const referenced = [
		...new Set(
			entries.flatMap((entry) =>
				[
					entry.names.path,
					entry.names.query,
					entry.names.header,
					entry.names.body,
					entry.names.response,
					entry.names.responses,
				].filter((name): name is string => name !== undefined),
			),
		),
	]
		.filter((identifier) => mentioned.has(identifier))
		.toSorted();
	const imports =
		referenced.length === 0
			? ""
			: `import {\n${referenced.map((id) => `\t${id},`).join("\n")}\n} from "./schemas.gen.js";\n`;

	/**
	 * One `Hono` per resource, declared before the routes and mounted after them.
	 *
	 * **Mounted AFTER, deliberately.** `app.route()` copies the sub-app's routes into the parent at
	 * the moment it is called, so mounting before the routes are registered mounts nothing, the same
	 * shape of defect as Hono middleware, which only applies to routes registered after it. Declaring
	 * at the top and mounting at the bottom is the arrangement that cannot be got wrong by reordering.
	 */
	/**
	 * **One chained expression per app, because that is the only shape `hc` can read.**
	 *
	 * Hono accumulates its `Schema` type through the chain, so a sub-app declared and then registered
	 * across separate statements throws every route's type away. Declaring it AS the chain keeps them,
	 * and mounting with a chained `.route()` carries them up into the parent.
	 *
	 * **The ordering property that used to need a comment is now structural.** Mounting before the
	 * routes were registered mounted nothing, and the fix was "declare at the top, mount at the
	 * bottom". A rule a reordering could break. A single expression cannot be reordered wrongly: the
	 * sub-app is complete at the point it is mounted because it is its own initialiser.
	 */
	const byTarget = new Map<string, string[]>();
	for (const registration of registrations) {
		byTarget.set(registration.target, [
			...(byTarget.get(registration.target) ?? []),
			registration.text,
		]);
	}
	const subAppDeclarations =
		subApps.size === 0
			? ""
			: `${[...subApps.values()]
					.map(
						(name) =>
							`\tconst ${name} = new Hono<AppEnv>()\n${(byTarget.get(name) ?? []).join("\n")};`,
					)
					.join("\n\n")}\n\n`;
	const subAppMounts = [...subApps].map(
		([resource, name]) => `\t\t.route(${JSON.stringify(`/${resource}`)}, ${name})`,
	);
	/**
	 * Everything that stays on the root, then every mount, as one returned chain.
	 *
	 * Returned rather than discarded: `registerRoutes` used to be `void`, and measured in a fresh
	 * project that made `hc<typeof app>` resolve to **`unknown`**. Hono's RPC client, which is one of
	 * the framework's headline features, was categorically unavailable to anything this emitter
	 * produced. Handing back the chained value costs nothing and restores it.
	 */
	const rootChain = [...(byTarget.get("app") ?? []), ...subAppMounts];

	// Imported only where a route actually negotiates: an unused import fails the repo's own lint.
	const negotiates = [...grouped.values()].some((group) => group.length > 1);
	// Same rule: imported only where a HEAD operation stands alone on its path.
	const guardsHead = registrations.some((registration) => registration.headOnly);
	/**
	 * **Which runtime imports to write is read from the DATA, never from the rendered text.**
	 *
	 * Matching a substring of generated output is how one of these went missing already: it tested for
	 * `byContentType([`, the emitted call gained arguments before its bracket, the substring stopped
	 * matching, the import stopped being written, and the emitted module threw
	 * `ReferenceError: byContentType is not defined` at registration. Nothing in the emitter objected,
	 * because the check was a string about a string.
	 *
	 * `guardsHead` above had the same shape, and the sibling library had it in a worse place, deciding
	 * whether a parameter gets a wire decoder by `declared.startsWith("z.number()")`. A literal union
	 * (`@query size: 10 | 25 | 50`) begins with neither prefix, so every conformant caller of that
	 * parameter got a 400 that no document comparison could see.
	 *
	 * The rendered text is still read to decide which VALIDATOR identifiers to import, and that one is
	 * safe in a way these are not: an identifier absent from the text is genuinely not needed, so the
	 * check cannot be wrong in the direction that breaks a build.
	 */
	const dispatchesBody = entries.some((entry) => entry.dispatched !== undefined);
	/**
	 * **Imported only where a route actually validates something, like every other value import here.**
	 *
	 * This one was unconditional while the three around it were not, and the comment above them stated
	 * the rule it was breaking. A service whose operations declare no parameters at all -- two bare
	 * `GET`s, which is where a health check starts and therefore where a new consumer starts -- emitted
	 * an import nothing used, and `tsp compile` reported success:
	 * `TS6133: 'zValidator' is declared but its value is never read`.
	 *
	 * Counted from the same filtered list the middleware is rendered from, so it cannot disagree with
	 * what was emitted: a dispatched body's validator is `byContentType`, not a `zValidator`.
	 */
	/**
	 * **`z` is only ever reached through `z.infer`**, which appears where an operation has an input
	 * type or a response body. A service whose every operation takes nothing and returns `void` names
	 * neither, so the import was written and never used:
	 * `TS6133: 'z' is declared but its value is never read`. Same shape as the `zValidator` one above,
	 * one step further along.
	 */
	const usesZod = entries.some(
		(entry) => inputTypeOf(entry) !== undefined || entry.names.response !== undefined,
	);
	const validates = entries.some(
		(entry) =>
			entry.validators.filter(
				([target]) => entry.dispatched === undefined || target !== VALIDATOR_TARGET.body,
			).length > 0,
	);
	const runtimeModule = JSON.stringify(emitted.options.runtimeModule);

	/**
	 * **One base sub-app, mounted with `app.route()`. Hono's own nesting, not a rewritten path on
	 * every registration.** Prefixing each path individually would fight the resource grouping, and
	 * would put the prefix in `hc`'s type surface as part of every route name rather than once. A
	 * nested `.route()` composes exactly, and the parent's `app.routes` still reports the fully
	 * composed path, which every arm that counts routes depends on.
	 */
	const usesBasePath = basePaths.length > 0;
	const needsHonoValue = subApps.size > 0 || usesBasePath;

	return `${generatedBanner(emitted.options.regenerateHint)}
${validates ? 'import { zValidator } from "@hono/zod-validator";\n' : ""}${needsHonoValue ? 'import { Hono } from "hono";\nimport type { Context, Input } from "hono";' : 'import type { Context, Hono, Input } from "hono";'}
${usesZod ? 'import { z } from "zod";\n' : ""}import type { AppEnv, Awaitable, Ctx, Result, RouteDeps } from ${runtimeModule};${negotiates ? `\nimport { selectContentType } from ${runtimeModule};` : ""}${guardsHead ? `\nimport { headOnly } from ${runtimeModule};` : ""}${dispatchesBody ? `\nimport { byContentType } from ${runtimeModule};` : ""}${mountsOptionalBody ? `\nimport { optionalBody } from ${runtimeModule};` : ""}
${imports}
/**
 * One method per operation, each concretely typed from the schemas it validates against.
 *
 * There is no cast anywhere in this file, and no dynamic lookup: the generated call sites name the
 * method, so an implementation whose input or output does not match the contract fails to compile.
 */
${fieldsHelper}${declaredHelper}export interface Operations {
${methods.join("\n")}
}

/**
 * One alias per operation, so a handler can live beside the module it belongs to.
 *
 * **Derived by indexed access, never restated.** An indexed access into Operations cannot drift
 * from the interface; a second hand-written signature could, and a signature that silently disagrees
 * with the contract is the whole failure mode this emitter exists to remove.
 */
${aliases.join("\n")}

/**
 * **There is deliberately NO exported HandlersFor alias to annotate the factory with.**
 *
 * There was one, and it silently disabled the guard below. Annotating widens the value to
 * Operations, so T infers as Operations, Exclude<keyof T, keyof Operations> is never, and the
 * surplus-key constraint evaporates. Measured: a handler for an operation the spec no longer
 * declares produced no error at all through the annotated form, and TS2345 without it.
 *
 * Write the factory unannotated, inference then carries the real shape into registerRoutes:
 *
 *     const handlersFor = (c) => backendFor(c.env);
 *     registerRoutes(app, handlersFor, deps);
 */

/**
 * Refuses a handler set carrying an operation the spec no longer declares.
 *
 * **Removal is the change the type system misses, and it is the one that matters most.** Adding an
 * operation is a missing property; changing one is a wrong signature; both fail loudly. Removing one
 * leaves a handler that compiles forever against a route nobody mounts.
 *
 * The excess-property check catches it, but ONLY on an object literal assigned straight to an
 * annotated target. Mapping every surplus key to never makes the refusal structural instead: a key
 * outside Operations can only be satisfied by a value that cannot exist.
 */
export type Exhaustive<T> = T & Record<Exclude<keyof T, keyof Operations>, never>;

/** Mount every operation the service declares. */
export function registerRoutes<T extends Operations>(
	app: Hono<AppEnv>,
	handlersFor: <P extends string, I extends Input>(c: Context<AppEnv, P, I>) => Exhaustive<T>,
	deps: RouteDeps,
) {
${subAppDeclarations}${
		usesBasePath
			? `\tconst basePathRoutes = new Hono<AppEnv>()\n${rootChain.join("\n")};\n\n\treturn app${basePaths.map((prefix) => `\n\t\t.route(${JSON.stringify(prefix)}, basePathRoutes)`).join("")};`
			: `\treturn app\n${rootChain.join("\n")};`
	}
}
`;
}
