import {
	objectKey,
	type EmittedRoute,
	type EmittedService,
	type RouteSchemaNames,
} from "typespec-http-zod";

/** The header every emitted file carries. */
const GENERATED_BANNER = `// GENERATED by typespec-hono from the TypeSpec service definition. DO NOT EDIT.
// Recompile the spec that produced it; edits here are overwritten on the next run.
`;

/** A parameter name Hono can carry verbatim — measured against Hono, not assumed. */
const PLAIN_PATH_PARAMETER = /^[A-Za-z0-9_.~-]+$/;

/**
 * TypeSpec publishes `/widgets/{widget-id}`; Hono routes on `/widgets/:widget-id`.
 *
 * ⚠️ **This used to match `\w+`, so any parameter carrying a hyphen was left ALONE.**
 * `@path("thing-id")` produced the literal route `/things/{thing-id}` — mounted, counted by every arm
 * that counts routes, and reachable by nobody. It answered 404 to the only requests it was for. Hono
 * handles `:thing-id` and `:x.y` perfectly well; the narrow character class was ours.
 *
 * A name that is not plain is REFUSED rather than approximated. Hono reads a parameter up to the next
 * `/`, so an RFC 6570 modifier would survive into the name and `*` would become Hono's wildcard — a
 * route that matches the wrong requests and answers them, which is worse than one that fails.
 *
 * ⚠️ **This runs at RENDER time, not during collection.** It used to run inside `collectRoutes`, which
 * put one framework's spelling into the shared intermediate representation and refused the whole
 * operation — validators included — over a template no router could mount. What a request body must
 * look like does not depend on that.
 */
export function toHonoPath(
	template: string,
	refuse: (template: string, name: string) => void,
): string {
	return template.replace(/\{([^}]+)\}/g, (match, name: string) => {
		if (PLAIN_PATH_PARAMETER.test(name)) return `:${name}`;
		refuse(template, name);
		return match;
	});
}

/**
 * Verbs Hono cannot dispatch to, whatever they are registered with.
 *
 * ⚠️ **`HEAD` is rewritten to `GET` before matching** — `hono-base.js` does it unconditionally at the
 * top of `#dispatch` — so a route registered under it is never reached. See the `unroutable-verb`
 * diagnostic for the measurements.
 */
const UNROUTABLE_VERBS = new Set(["HEAD"]);

/** `GET` → `get`. Hono's per-verb helpers are the idiom; `app.on` is the escape hatch. */
const HONO_METHOD: Readonly<Record<string, string>> = {
	GET: "get",
	POST: "post",
	PUT: "put",
	PATCH: "patch",
	DELETE: "delete",
};

/**
 * A request location, as the DOCUMENT names it, mapped to the target `@hono/zod-validator` reads.
 *
 * ⚠️ **The two vocabularies are not the same, and only one of them is a contract fact.** OpenAPI says
 * `path`, `query`, `header` and a request body; zValidator says `param`, `query`, `header` and
 * `json`. The library publishes the first because that is what the document states; translating is
 * this package's job, and it is a map rather than a coincidence.
 */
const VALIDATOR_TARGET = {
	path: "param",
	query: "query",
	header: "header",
	body: "json",
} as const;

interface AppRoute {
	readonly route: EmittedRoute;
	readonly names: RouteSchemaNames;
	/** `[zValidator target, the identifier holding its schema]`, in the order they are applied. */
	readonly validators: readonly (readonly [string, string])[];
}

/**
 * Everything an operation's input is made of, as a TypeScript type built from the schemas the library
 * declared.
 *
 * `z.infer` rather than a restatement: the handler receives exactly what the validators produced, so
 * deriving the type from the same consts is what makes the call site check itself. A restated
 * interface would be a second source of truth that drifts.
 */
function inputTypeOf(entry: AppRoute): string | undefined {
	const parts = entry.validators.map(([, name]) => `z.infer<typeof ${name}>`);
	if (entry.route.rawBodyProperty !== undefined) {
		parts.push(`{ ${objectKey(entry.route.rawBodyProperty)}: string }`);
	}
	return parts.length === 0 ? undefined : parts.join(" & ");
}

/**
 * `getWidget` -> `GetWidget`, `Avatar_getAvatarAsJson` -> `Avatar_getAvatarAsJson`.
 *
 * Only the first character moves. An operation id is already the name the DOCUMENT publishes, and
 * rewriting more of it would invent a second spelling of a contract fact for the sake of house style
 * — the `_` that `resolveOperationId` inserts is part of the published name.
 */
function capitaliseId(operationId: string): string {
	return `${operationId.charAt(0).toUpperCase()}${operationId.slice(1)}`;
}

/** The two things a Hono server cannot express, handed back rather than thrown. */
export interface RenderRefusals {
	readonly unsupportedPathTemplate: (route: EmittedRoute, template: string, name: string) => void;
	readonly unroutableVerb: (route: EmittedRoute) => void;
}

/**
 * The generated Hono server.
 *
 * ⚠️ **This replaces a data table that a hand-written loop interpreted at run time.** The emitter knew,
 * per operation, which validators applied and what the call looked like — and then flattened all of it
 * into one homogeneous array, so the consumer had to recover it dynamically and could not. Emitting
 * the call sites keeps that knowledge, and every one of them is monomorphic and checked.
 *
 * ⚠️ **Plain `Hono` and `@hono/zod-validator`, deliberately not `@hono/zod-openapi`.** The latter is
 * the same validation plus a document generated FROM the code — spec-last, and a second source of
 * truth competing with the one `@typespec/openapi3` publishes from the spec. We want its validation,
 * not its documentation.
 *
 * ⚠️ **It declares no schema of its own.** Every validator this file names was declared by
 * `typespec-http-zod` into `schemas.gen.ts` and is imported by name. That is what makes the two
 * packages one emitter rather than two that must agree by coincidence — and it is why a consumer who
 * wants the validators without a server can simply not install this one.
 */
export function renderApp(emitted: EmittedService, refuse: RenderRefusals): string {
	const entries: AppRoute[] = emitted.routes.flatMap((route) => {
		/**
		 * ⚠️ **Refused AND skipped, in that order.** Emitting the route anyway would put a registration
		 * in the file that `app.routes` lists and Hono never dispatches to — which is precisely how
		 * fifteen unreachable routes passed a differential written to catch unreachable routes.
		 */
		if (UNROUTABLE_VERBS.has(route.verb)) {
			refuse.unroutableVerb(route);
			return [];
		}
		const names = emitted.schemaNames.get(route.operationId);
		// The library declares a `Responses` const for every operation, so a missing entry is a bug in
		// this package's pairing rather than a spec the emitter chose not to serve.
		if (names === undefined) return [];
		const validators: (readonly [string, string])[] = [];
		for (const location of ["path", "query", "header", "body"] as const) {
			const identifier = names[location];
			if (identifier !== undefined) validators.push([VALIDATOR_TARGET[location], identifier]);
		}
		return [{ route, names, validators }];
	});

	/**
	 * ⚠️ **One registration per verb+path, not per operation.**
	 *
	 * TypeSpec models content negotiation as several operations on one route; OpenAPI models it as one
	 * path entry whose response lists every media type. This emitter used to register all of them, and
	 * Hono matches in registration order — so every operation after the first was dead code that looked
	 * mounted, and the only symptom was an operation count two higher than the document's.
	 */
	const grouped = new Map<string, AppRoute[]>();
	for (const entry of entries) {
		const slot = `${entry.route.verb} ${entry.route.path}`;
		grouped.set(slot, [...(grouped.get(slot) ?? []), entry]);
	}

	const methods = entries.map((entry) => {
		const { route, names } = entry;
		/**
		 * A negotiated member's `accept` is not in its validator — the negotiation supplies it — but it
		 * IS in the operation's declared input, so the interface has to keep it. The literal is known
		 * exactly: it is the only value that reaches this member.
		 */
		const negotiated =
			(grouped.get(`${route.verb} ${route.path}`)?.length ?? 0) > 1 && route.accept !== undefined
				? `{ ${objectKey(route.accept.name)}: ${JSON.stringify(route.accept.value)} }`
				: undefined;
		const validated = inputTypeOf(entry);
		const input =
			negotiated === undefined
				? validated
				: validated === undefined
					? negotiated
					: `${validated} & ${negotiated}`;
		const output = names.response === undefined ? "void" : `z.infer<typeof ${names.response}>`;
		const signature = input === undefined ? "ctx: Ctx" : `ctx: Ctx, input: ${input}`;
		const doc = route.summary === undefined ? "" : `\t/** ${route.summary} */\n`;
		return `${doc}\t${route.operationId}(${signature}): Awaitable<Result<${output}>>;`;
	});

	const aliases = entries.map(
		(entry) =>
			`export type ${capitaliseId(entry.route.operationId)}Handler = Operations[${JSON.stringify(entry.route.operationId)}];`,
	);

	const registrations = [...grouped.values()].map((group) => {
		const entry = group[0] as AppRoute;
		const { route, validators } = entry;
		const method = HONO_METHOD[route.verb] ?? "on";
		const path = toHonoPath(route.path, (template, name) =>
			refuse.unsupportedPathTemplate(route, template, name),
		);
		/**
		 * The scope gate goes FIRST, before any validator.
		 *
		 * A caller without the scope must be refused whatever their body looks like: validating first
		 * answers `400` to a request the contract says is not theirs to make, which tells somebody who
		 * may not call the operation at all which payloads are well-formed.
		 */
		const gate =
			route.scopes.length === 0
				? []
				: [`\t\tdeps.authorize([${route.scopes.map((s) => JSON.stringify(s)).join(", ")}]),`];
		const middleware = [
			...gate,
			...validators.map(
				([target, name]) => `\t\tzValidator(${JSON.stringify(target)}, ${name}, deps.invalid),`,
			),
		];
		/**
		 * Whether the operation requires a caller — and NOTHING else about the caller.
		 *
		 * ⚠️ **This used to pass `"account"` or `"resource"`, chosen by how many path parameters the
		 * route had, and that was a rule no document states.** `@useAuth(NoAuth)` reaches OpenAPI as
		 * `security: []`, so "does this need a caller" is a contract fact and is generated. "Is this
		 * account-scoped or resource-scoped" is not: no OpenAPI keyword expresses it, and the
		 * path-parameter heuristic happened to fit the first consumer.
		 */
		const body: string[] = [];
		if (route.noAuth !== true) {
			body.push(`\t\t\tconst ctx = deps.context(c, "required");`);
			body.push("\t\t\tif (ctx === null) return deps.noContext(c);");
		} else {
			body.push(`\t\t\tconst ctx = deps.context(c, "none") as Ctx;`);
		}
		const pieces = validators.map(([target]) => `...c.req.valid(${JSON.stringify(target)})`);
		if (route.rawBodyProperty !== undefined) {
			// The bytes ARE the contract: a signature covers exactly what arrived, so parsing and
			// re-serialising would verify a different string than the sender signed.
			pieces.push(`${objectKey(route.rawBodyProperty)}: await c.req.text()`);
		}
		const invoke = (member: AppRoute): string => {
			// The member's own `accept` literal, which its input type requires and which the shared
			// validator no longer supplies. We know it exactly: it is the branch we are in.
			const own =
				group.length > 1 && member.route.accept !== undefined
					? [`${objectKey(member.route.accept.name)}: ${JSON.stringify(member.route.accept.value)}`]
					: [];
			const input = [...pieces, ...own];
			const call =
				input.length === 0
					? `handlersFor(c).${member.route.operationId}(ctx)`
					: `handlersFor(c).${member.route.operationId}(ctx, { ${input.join(", ")} })`;
			return `deps.respond(c, ${member.names.responses}, await ${call})`;
		};

		if (group.length === 1) {
			body.push(`\t\t\treturn ${invoke(entry)};`);
		} else {
			/**
			 * Several operations, one route: the caller's `Accept` chooses which one answers.
			 *
			 * The offered list and which operation serves each type are both read from the document.
			 * `selectContentType` applies RFC 9110 §12.5.1 to them — it lives in the runtime rather than
			 * in `deps` because both halves are derivable, and an app forced to supply it would be
			 * re-implementing the standard.
			 */
			const offers = group.flatMap((member) =>
				member.route.responseContentTypes.map((contentType) => ({ contentType, member })),
			);
			const offered = `[${offers.map((offer) => JSON.stringify(offer.contentType)).join(", ")}]`;
			body.push(`\t\t\tconst served = selectContentType(c.req.header("accept"), ${offered});`);
			body.push(`\t\t\tif (served === undefined) return deps.notAcceptable(c, ${offered});`);
			for (const offer of offers) {
				body.push(
					`\t\t\tif (served === ${JSON.stringify(offer.contentType)}) return ${invoke(offer.member)};`,
				);
			}
			// `selectContentType` only ever returns a member of the list it was given, so this is
			// unreachable — and stating that is cheaper than a cast that would hide it if it were not.
			body.push(`\t\t\treturn deps.notAcceptable(c, ${offered});`);
		}
		/**
		 * ⚠️ **`app.on` takes the METHOD first, and we were not passing one.** Only five verbs have a
		 * dedicated Hono method; everything else — `HEAD`, `OPTIONS`, anything a spec invents — fell
		 * through to `app.on(path, handler)`, which Hono reads as `on(method, path)`. The route was
		 * emitted, counted by every arm that counted rows, and mounted nowhere.
		 */
		return [
			`\tapp.${method}(`,
			...(method === "on" ? [`\t\t${JSON.stringify(route.verb)},`] : []),
			`\t\t${JSON.stringify(path)},`,
			...middleware,
			"\t\tasync (c) => {",
			...body,
			"\t\t},",
			"\t);",
		].join("\n");
	});

	/**
	 * Every identifier this file names, imported from the module that declares it.
	 *
	 * ⚠️ **Derived from what the rendered text actually references, not from what was available.** An
	 * unused import fails the lint a generated file has to pass like any other, and a missing one is a
	 * file that does not compile. Both have happened.
	 */
	const rendered = [...registrations, ...methods, ...aliases].join("\n");
	const referenced = [
		...new Set(
			entries.flatMap((entry) =>
				[
					entry.names.path,
					entry.names.query,
					entry.names.header,
					entry.names.body,
					entry.names.response,
					entry.names.responses,
				].filter((name): name is string => name !== undefined),
			),
		),
	]
		.filter((identifier) => new RegExp(`\\b${identifier}\\b`).test(rendered))
		.toSorted();
	const imports =
		referenced.length === 0
			? ""
			: `import {\n${referenced.map((id) => `\t${id},`).join("\n")}\n} from "./schemas.gen.js";\n`;

	// Imported only where a route actually negotiates: an unused import fails the repo's own lint.
	const negotiates = [...grouped.values()].some((group) => group.length > 1);
	const runtimeModule = JSON.stringify(emitted.options.runtimeModule);

	return `${GENERATED_BANNER}
import { zValidator } from "@hono/zod-validator";
import type { Context, Hono, Input } from "hono";
import { z } from "zod";
import type { AppEnv, Awaitable, Ctx, Result, RouteDeps } from ${runtimeModule};${negotiates ? `\nimport { selectContentType } from ${runtimeModule};` : ""}
${imports}
/**
 * One method per operation, each concretely typed from the schemas it validates against.
 *
 * There is no cast anywhere in this file, and no dynamic lookup: the generated call sites name the
 * method, so an implementation whose input or output does not match the contract fails to compile.
 */
export interface Operations {
${methods.join("\n")}
}

/**
 * One alias per operation, so a handler can live beside the module it belongs to.
 *
 * ⚠️ **Derived by indexed access, never restated.** An indexed access into Operations cannot drift
 * from the interface; a second hand-written signature could, and a signature that silently disagrees
 * with the contract is the whole failure mode this emitter exists to remove.
 */
${aliases.join("\n")}

/**
 * ⚠️ **There is deliberately NO exported HandlersFor alias to annotate the factory with.**
 *
 * There was one, and it silently disabled the guard below. Annotating widens the value to
 * Operations, so T infers as Operations, Exclude<keyof T, keyof Operations> is never, and the
 * surplus-key constraint evaporates. Measured: a handler for an operation the spec no longer
 * declares produced no error at all through the annotated form, and TS2345 without it.
 *
 * Write the factory unannotated — inference then carries the real shape into registerRoutes:
 *
 *     const handlersFor = (c) => backendFor(c.env);
 *     registerRoutes(app, handlersFor, deps);
 */

/**
 * Refuses a handler set carrying an operation the spec no longer declares.
 *
 * ⚠️ **Removal is the change the type system misses, and it is the one that matters most.** Adding an
 * operation is a missing property; changing one is a wrong signature; both fail loudly. Removing one
 * leaves a handler that compiles forever against a route nobody mounts.
 *
 * The excess-property check catches it, but ONLY on an object literal assigned straight to an
 * annotated target. Mapping every surplus key to never makes the refusal structural instead: a key
 * outside Operations can only be satisfied by a value that cannot exist.
 */
export type Exhaustive<T> = T & Record<Exclude<keyof T, keyof Operations>, never>;

/** Mount every operation the service declares. */
export function registerRoutes<T extends Operations>(
	app: Hono<AppEnv>,
	handlersFor: <P extends string, I extends Input>(c: Context<AppEnv, P, I>) => Exhaustive<T>,
	deps: RouteDeps,
): void {
${registrations.join("\n")}
}
`;
}
