import { emitFile, NoTarget, resolvePath, type EmitContext, type Type } from "@typespec/compiler";
import type { EmittedService } from "typespec-http-zod";
import type { HttpOperation } from "@typespec/http";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { emitHttpZod } from "typespec-http-zod";
import { renderApp } from "./app.js";
import { resolveBasePath } from "./base-path.js";
import { reportDiagnostic } from "./lib.js";

/**
 * This emitter's entry point. **the whole of `typespec-http-zod`, plus one file**.
 *
 * **A consumer lists ONE emitter, and this is why.** The validators and the server share a naming
 * contract: `app.gen.ts` imports `readWidgetPath` and `readWidgetResponses` from `schemas.gen.js` by
 * name. Two separate TypeSpec emitters would each get their own `$onEmit` and their own registry, and
 * would have to arrive at identical identifiers by coincidence. Running the library here means it
 * mints the names, writes them, and hands them back, so agreement is structural rather than hoped
 * for.
 *
 * **It uses nothing `typespec-http-zod` does not export.** The package's `exports` map makes a deep
 * import impossible, so this file is the proof that the published API is sufficient to build a server
 * generator on. Anything it cannot do from here is a gap in that API, to be fixed there.
 */
/**
 * The HTTP operation an emitted route came from, keyed on verb and path.
 *
 * **Keyed on the ROUTE, not on the name, and the name was wrong for every interface.**
 * `EmittedRoute.operationId` is the id the document publishes, `Accounts_list`, with the interface
 * prefix `resolveOperationId` inserts, while `operation.operation.name` is the bare `list`. Matching
 * them never succeeded for an operation declared inside an `interface`, which is most of them.
 *
 * Two things rested on that lookup and both were silently wrong: every diagnostic pointed at the
 * service namespace instead of the operation that caused it, and the security requirements resolved
 * to none, so a scheme-gated route emitted no gate. Verb and path identify a route exactly, and are
 * what both sides already agree on.
 */
function operationFor(
	emitted: EmittedService,
	verb: string,
	path: string,
): HttpOperation | undefined {
	return emitted.service.operations.find(
		(candidate) => candidate.verb.toUpperCase() === verb.toUpperCase() && candidate.path === path,
	);
}

/** The declaration a diagnostic should point at, falling back to the service when it cannot be found. */
function targetFor(emitted: EmittedService, verb: string, path: string): Type {
	return operationFor(emitted, verb, path)?.operation ?? emitted.service.namespace;
}

/** The header the emitted runtime carries, matching every other generated file. */
function generatedRuntimeBanner(hint: string | undefined): string {
	const second =
		hint === undefined
			? "// A copy of this package's runtime, emitted so the generated code imports no package at run time."
			: `// Regenerate with: ${hint}`;
	return `// GENERATED by typespec-hono. DO NOT EDIT.
${second}
`;
}

/**
 * The generated runtime lands beside the generated code, so nothing the emitter writes imports this
 * package at run time.
 *
 * An emitter is a build-time tool. `@typespec/openapi3` is a devDependency and its output imports
 * nothing, which is the shape a consumer expects. This package shipped a runtime half instead, which
 * forced it to be a `dependency` and made `--save-dev` fail at deploy and nowhere earlier. Emitting
 * the runtime removes the choice rather than documenting it.
 *
 * **Always this module.** `runtime-module` used to replace it, and that made an application own a
 * copy of generated logic - see the `runtime-module-removed` diagnostic.
 */
export { DEFAULT_RUNTIME_MODULE } from "./app.js";

/** Where this package's own runtime source lives, to be copied beside the generated code. */
const RUNTIME_SOURCE = fileURLToPath(new URL("../../src/runtime.ts", import.meta.url));

/**
 * The options with `runtime-module` refused and removed, at the top level and per service.
 *
 * **Removed, not only reported**, because the library validates nothing about a key it no longer
 * declares, and a wrapper passing options through should not hand it one.
 */
function withoutRuntimeModule(context: EmitContext): EmitContext {
	const options = context.options as Record<string, unknown> & {
		services?: Record<string, Record<string, unknown>>;
	};
	const refuse = (value: unknown): void => {
		reportDiagnostic(context.program, {
			code: "runtime-module-removed",
			format: { value: String(value) },
			target: NoTarget,
		});
	};
	const { "runtime-module": topLevel, services, ...rest } = options;
	if (topLevel !== undefined) refuse(topLevel);
	const kept =
		services === undefined
			? undefined
			: Object.fromEntries(
					Object.entries(services).map(([name, service]) => {
						const { "runtime-module": perService, ...others } = service;
						if (perService !== undefined) refuse(perService);
						return [name, others];
					}),
				);
	return {
		...context,
		options: kept === undefined ? rest : { ...rest, services: kept },
	} as EmitContext;
}

export async function $onEmit(context: EmitContext): Promise<void> {
	for (const emitted of await emitHttpZod(withoutRuntimeModule(context))) {
		await emitFile(context.program, {
			path: resolvePath(emitted.outputDir, "runtime.gen.ts"),
			content: `${generatedRuntimeBanner(emitted.options.regenerateHint)}${readFileSync(RUNTIME_SOURCE, "utf8")}`,
		});
		/**
		 * **The path the DOCUMENT says this service is served under.** An OpenAPI path is relative to
		 * its server, so `@server("/api/v1")` plus `/accounts` publishes `/api/v1/accounts`. Mounting at
		 * the root made every client generated from the document 404.
		 */
		/**
		 * **A service this project does not serve still belongs in the program.**
		 *
		 * One compile is what makes a shared vocabulary shared, so a surface not yet served is in the
		 * spec for its types and its validators. Its server is not wanted, and without a way to say so
		 * the emitter wrote an `app.gen.ts` the project had to keep honest with probe tests and never
		 * mounted.
		 *
		 * Only this file is withheld. Everything the library emits for that service is untouched,
		 * because those are the reason it is in the program at all.
		 */
		const serviceName = emitted.service.namespace.name;
		if (context.options.services?.[serviceName]?.["emit-server"] === false) continue;
		const base = resolveBasePath(context.program, emitted.service.namespace);
		await emitFile(context.program, {
			path: resolvePath(emitted.outputDir, "app.gen.ts"),
			content: renderApp(
				emitted,
				{
					/**
					 * Reported rather than thrown, so a spec with one unmountable path still names every
					 * other problem in the same compile, and so the validators for the rest of the service
					 * are still written. A path this router cannot express is not a reason to emit nothing.
					 */
					unsupportedPathTemplate: (route, template, name) => {
						reportDiagnostic(context.program, {
							code: "unsupported-path-template",
							format: { template, name },
							target: targetFor(emitted, route.verb, route.path),
						});
					},
					unvalidatedResponseMediaType: (route, status, types) => {
						reportDiagnostic(context.program, {
							code: "unvalidated-response-media-type",
							format: {
								operationId: route.operationId,
								status: String(status),
								types: types.join(", "),
							},
							target: targetFor(emitted, route.verb, route.path),
						});
					},
					unvalidatableMediaType: (route, types) => {
						reportDiagnostic(context.program, {
							code: "unvalidatable-media-type",
							format: { operationId: route.operationId, types: types.join(", ") },
							target: targetFor(emitted, route.verb, route.path),
						});
					},
				},
				base.basePaths,
			),
		});
	}
}
